meta_product_name: "deux mille dix neuf"
meta_title: "deux mille dix neuf - maxi calendrier pour l'année 2019"
meta_description: "maxi calendrier un peu géant à accrocher chez soi pour ne rater absolument aucun évenement."
meta_image: "deuxmilledixneuf-fb-cover.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@camvillard"
